# Generated by Django 5.1.7 on 2025-03-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmployeeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Nome")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("adress", models.TextField(verbose_name="Endereco")),
                ("phone", models.CharField(max_length=13, verbose_name="Telefone")),
            ],
        ),
    ]
